kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebind-for-deploy
subjects:
  - kind: ServiceAccount
    name: lovechedule-pipeline-sa
    namespace: lovechedule
roleRef:
  kind: ClusterRole
  name: role-for-tektondeploy
  apiGroup: rbac.authorization.k8s.io