apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-commit
  namespace: lovechedule
spec:
  params:
    - name: gitRepoUrl
      description: "Git repository URL for the Helm manifest"
      type: string
    - name: gitRevision
      description: "Git branch or tag to commit (e.g. main)"
      type: string
    - name: chartDirectory
      description: "Directory of the Helm chart in the repository"
      type: string
    - name: chartValuesFile
      description: "Values file in the Helm chart to update with the new image tag"
      type: string
    - name: imageTag
      description: "New image tag to update in the Helm manifest"
      type: string

  workspaces:
    - name: source
      description: "Workspace containing the source code"
    - name: basic-auth
      description: "Workspace containing .git-credentials and .gitconfig for HTTPS authentication"
      optional: true

  steps:
    - name: update-manifest
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        set -x

        # Configure HTTPS authentication if available
        if [ -d /workspace/basic-auth ]; then
          cp /workspace/basic-auth/.git-credentials /root/.git-credentials
          cp /workspace/basic-auth/.gitconfig /root/.gitconfig
        fi

        # Clone the repository
        git clone $(params.gitRepoUrl) $(workspaces.source.path)/repo
        cd $(workspaces.source.path)/repo

        # Checkout the target branch
        git checkout $(params.gitRevision)

        # Update image tag in the Helm values file
        sed -i "s|tag: .*|tag: \"$(params.imageTag)\"|" $(params.chartDirectory)/$(params.chartValuesFile)

        # Commit the change
        git config user.name "tnqls0624"
        git config user.email "dktnqls0624@naver.com"
        git add $(params.chartDirectory)/$(params.chartValuesFile)
        git commit -m "Update image tag to $(params.imageTag)"
        git push origin $(params.gitRevision)

  results:
    - name: commit-sha
      description: "The SHA of the commit that was created"
