apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
  namespace: lovechedule
spec:
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: gitRepoUrl
      description: "Git repository URL for the Helm manifest"
      type: string
    - name: gitRevision
      description: "Git branch or tag to commit (e.g. main)"
      type: string
    - name: chartDirectory
      description: "Directory of the Helm chart in the repository"
      type: string
    - name: chartValuesFile
      description: "Values file in the Helm chart to update with the new image tag"
      type: string

  workspaces:
    - name: shared-data
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)

    - name: build-push
      runAfter: ["check-dockerfile"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKERFILE
          value: Dockerfile # Dockerfile의 위치를 명확히 지정
        - name: CONTEXT
          value: . # 빌드 컨텍스트 경로

    - name: update-manifest-commit
      runAfter: ["build-push"]
      taskRef:
        name: update-manifest-commit
      params:
        - name: gitRepoUrl
          value: $(params.gitRepoUrl)
        - name: gitRevision
          value: $(params.gitRevision)
        - name: chartDirectory
          value: $(params.chartDirectory)
        - name: chartValuesFile
          value: $(params.chartValuesFile)
        - name: imageTag
          value: $(params.image-reference)
      workspaces:
        - name: source
          workspace: shared-data