apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-read-run-1 # make name automate with random index ( for re use pipelinerun yaml )
  namespace: lovechedule
spec:
  serviceAccountName: lovechedule-pipeline-sa # sa for git credientials -> pipeline will use for clone private repo
  pipelineRef: # select pipeline
    name: clone-read
  podTemplate: # setting taskpod
    securityContext:  # pod security
      fsGroup: 65532 # set volume owner gid = 65532
  workspaces: # volume for clone code
    - name: shared-data
      persistentVolumeClaim:
        claimName: lovechedule-pvc
#      volumeClaimTemplate: # automatically create pvc -> create pv
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          storageClassName: shared-data
#          resources:
#            requests:
#              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params: # git address
    - name: repo-url
      value: "https://github.com/tnqls0624/lovechedule-infra.git"
    - name: image-reference
      value: "dktnqls0624/project:latest"
    - name: kubectl-args
      value:
        - "apply"
        - "-f"
        - "test.yaml"