apiVersion: v1
kind: PersistentVolume
metadata:
  name: lovechedule-pv3
  namespace: lovechedule
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-070235316c7a1f8d1
