apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lovechedule-pvc
  namespace: lovechedule
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual