apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lovechedule-pvc2
  namespace: lovechedule
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: lovechedule-ebs-sc
