apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lovechedule-pvc2
  namespace: lovechedule
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # PV와 동일한 스토리지 클래스

