apiVersion: v1
kind: ServiceAccount
metadata:
  name: lovechedule-pipeline-sa
  namespace: lovechedule
secrets:
  - name: regcred #docker
  - name: github-credential
imagePullSecrets:
  - name: regcred
