apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
<<<<<<< HEAD
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # 디폴트 스토리지 클래스 설정
provisioner: ebs.csi.aws.com  # EBS CSI 드라이버 사용
parameters:
  type: gp3  # gp2 대신 gp3 사용을 권장
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
=======
  name: lovechedule-ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
>>>>>>> origin/main
