apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: lovechedule-tt
  namespace: lovechedule
spec:
  params:
    - name: giturl
    - name: imagetag
    - name: gitRepoUrl
    - name: gitRevision
    - name: chartDirectory
    - name: chartValuesFile
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        namespace: lovechedule
        generateName: lovechedule-cicd-run-
      spec:
        serviceAccountName: lovechedule-pipeline-sa
        pipelineRef:
          name: clone-read
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
          - name: shared-data
            persistentVolumeClaim:
              claimName: lovechedule-pvc2
          - name: docker-credentials
            secret:
              secretName: regcred
          - name: basic-auth
            secret:
              secretName: github-credential
        params:
          - name: repo-url
            value: $(tt.params.giturl)
          - name: image-reference
            value: dktnqls0624/project:$(tt.params.imagetag)
          - name: gitRepoUrl
            value: https://github.com/tnqls0624/lovechedule-manifest
          - name: gitRevision
            value: main
          - name: chartDirectory
            value: lovechedule-chart
          - name: chartValuesFile
            value: values.yaml
