apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: triggers-role
  namespace: lovechedule
rules:
  # Tekton 트리거 리소스 권한 설정
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "interceptors", "triggers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["create"]
  # ConfigMap과 Secrets 권한
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  # 서비스 어카운트의 인증 권한
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["impersonate"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trigger-cluster-role
rules:
  # EventListeners가 cluster-wide 리소스 접근이 필요할 때
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings", "clusterinterceptors"]
    verbs: ["get", "list", "watch"]

