apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: lovechedule-tb
  namespace: lovechedule
spec:
  params:
  - name: imagetag
    value: $(body.head_commit.id)
  - name: giturl
    value: $(body.repository.url)
